/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type AddressCreate struct {
	AddressBook bool `json:"address_book,omitempty"`
	AdministrativeArea string `json:"administrative_area,omitempty"`
	Borough string `json:"borough,omitempty"`
	BusinessName string `json:"business_name"`
	CountryCode string `json:"country_code"`
	CustomerReference string `json:"customer_reference,omitempty"`
	ExtendedAddress string `json:"extended_address,omitempty"`
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	Locality string `json:"locality"`
	Neighborhood string `json:"neighborhood,omitempty"`
	PhoneNumber string `json:"phone_number,omitempty"`
	PostalCode string `json:"postal_code,omitempty"`
	StreetAddress string `json:"street_address"`
	ValidateAddress bool `json:"validate_address,omitempty"`
}
