/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type Location struct {
	// Address of the location. Only displayed if name is present.
	Address string `json:"address"`
	// Latitude of the location
	Latitude string `json:"latitude"`
	// Longitude of the location
	Longitude string `json:"longitude"`
	// Name of the location
	Name string `json:"name"`
}
