/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

// This object represents an Over the Air (OTA) update request. It allows tracking the current status of a operation that apply settings in a particular SIM card. <br/><br/>
type CompleteOtaUpdate struct {
	// ISO 8601 formatted date-time indicating when the resource was created.
	CreatedAt string `json:"created_at,omitempty"`
	// Identifies the resource.
	Id string `json:"id,omitempty"`
	RecordType string `json:"record_type,omitempty"`
	Settings *CompleteOtaUpdateSettings `json:"settings,omitempty"`
	// The identification UUID of the related SIM card resource.
	SimCardId string `json:"sim_card_id,omitempty"`
	Status string `json:"status,omitempty"`
	// Represents the type of the operation requested. This will relate directly to the source of the request.
	Type_ string `json:"type,omitempty"`
	// ISO 8601 formatted date-time indicating when the resource was updated.
	UpdatedAt string `json:"updated_at,omitempty"`
}
