/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type MarkMessageAsReadRequestBody struct {
	Status string `json:"status"`
	// The user's WhatsApp ID.
	WhatsappUserId string `json:"whatsapp_user_id"`
}
