/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type PortingOrderPhoneNumberConfiguration struct {
	// identifies the connection to set on the numbers when ported
	ConnectionId string `json:"connection_id,omitempty"`
	// identifies the emergency address to set on the numbers when ported
	EmergencyAddressId string `json:"emergency_address_id,omitempty"`
	// identifies the messaging profile to set on the numbers when ported
	MessagingProfileId string `json:"messaging_profile_id,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
