/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type MessagingProfileHighLevelMetricsOutbound struct {
	// The number of outbound messages successfully delivered.
	Delivered float64 `json:"delivered,omitempty"`
	// The ratio of messages sent that resulted in errors.
	ErrorRatio float64 `json:"error_ratio,omitempty"`
	// The number of outbound messages sent.
	Sent float64 `json:"sent,omitempty"`
}
