/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

// The call forwarding settings for a phone number.
type CallForwarding struct {
	// Indicates if call forwarding will be enabled for this number if forwards_to and forwarding_type are filled in. Defaults to true for backwards compatibility with APIV1 use of numbers endpoints.
	CallForwardingEnabled bool `json:"call_forwarding_enabled,omitempty"`
	// Call forwarding type. 'forwards_to' must be set for this to have an effect.
	ForwardingType string `json:"forwarding_type,omitempty"`
	// The phone number to which inbound calls to this number are forwarded. Inbound calls will not be forwarded if this field is left blank. If set, must be a +E.164-formatted phone number.
	ForwardsTo string `json:"forwards_to,omitempty"`
}
