/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
import (
	"time"
)

type CallHangupPayload struct {
	// Call ID used to issue commands via Call Control API.
	CallControlId string `json:"call_control_id,omitempty"`
	// ID that is unique to the call and can be used to correlate webhook events.
	CallLegId string `json:"call_leg_id,omitempty"`
	// ID that is unique to the call session and can be used to correlate webhook events.
	CallSessionId string `json:"call_session_id,omitempty"`
	// State received from a command.
	ClientState string `json:"client_state,omitempty"`
	// Call Control App ID (formerly Telnyx connection ID) used in the call.
	ConnectionId string `json:"connection_id,omitempty"`
	// Number or SIP URI placing the call.
	From string `json:"from,omitempty"`
	// The reason the call was ended (`call_rejected`, `normal_clearing`, `originator_cancel`, `timeout`, `time_limit`, `user_busy`, `not_found` or `unspecified`).
	HangupCause string `json:"hangup_cause,omitempty"`
	// The party who ended the call (`callee`, `caller`, `unknown`).
	HangupSource string `json:"hangup_source,omitempty"`
	// The reason the call was ended (SIP response code). If the SIP response is unavailable (in inbound calls for example) this is set to `unspecified`.
	SipHangupCause string `json:"sip_hangup_cause,omitempty"`
	// ISO 8601 datetime of when the call started.
	StartTime time.Time `json:"start_time,omitempty"`
	// State received from a command.
	State string `json:"state,omitempty"`
	// Destination number or SIP URI of the call.
	To string `json:"to,omitempty"`
}
