/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
import (
	"time"
)

type MdrPostDetailReportRequest struct {
	Connections []int64 `json:"connections,omitempty"`
	Directions []string `json:"directions,omitempty"`
	EndDate time.Time `json:"end_date"`
	Filters []Filter `json:"filters,omitempty"`
	IncludeMessageBody bool `json:"include_message_body,omitempty"`
	Profiles string `json:"profiles,omitempty"`
	RecordTypes []string `json:"record_types,omitempty"`
	ReportName string `json:"report_name,omitempty"`
	StartDate time.Time `json:"start_date"`
}
