/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
// FqdnConnectionTransportProtocol : One of UDP, TLS, or TCP. Applies only to connections with IP authentication or FQDN authentication.
type FqdnConnectionTransportProtocol string

// List of FqdnConnectionTransportProtocol
const (
	UDP_FqdnConnectionTransportProtocol FqdnConnectionTransportProtocol = "UDP"
	TCP_FqdnConnectionTransportProtocol FqdnConnectionTransportProtocol = "TCP"
	TLS_FqdnConnectionTransportProtocol FqdnConnectionTransportProtocol = "TLS"
)
