/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
import (
	"time"
)

// A Collection of Notification Channels
type NotificationProfile struct {
	// ISO 8601 formatted date indicating when the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// A UUID.
	Id string `json:"id,omitempty"`
	// A human readable name.
	Name string `json:"name,omitempty"`
	// ISO 8601 formatted date indicating when the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
