/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/WunderkindNYC/telnyx-go

type InlineResponse20026DataFeatures struct {
	Sms *InlineResponse20026DataFeaturesSms `json:"sms,omitempty"`
	Mms *InlineResponse20026DataFeaturesSms `json:"mms,omitempty"`
}
