/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

// The current status or failure details of the SIM card's public IP.
type SimCardPublicIpStatus struct {
	// This attribute is an <a href=\"https://developers.telnyx.com/docs/api/v2/overview#errors\">error code</a> related to the failure reason.
	ErrorCode string `json:"error_code,omitempty"`
	// This attribute provides a human-readable explanation of why a failure happened.
	ErrorDescription string `json:"error_description,omitempty"`
	// The current status or failure details of the SIM card's public IP. <ul>  <li><code>provisioning</code> - the IP is being provisioned.</li>  <li><code>provisioned</code> - the IP was provisioned and the SIM is reachable on the public internet.</li>  <li><code>failed</code> - the provisioning had failed for a reason and it requires an intervention.</li>  <li><code>decommissioning</code> - the public IP is being removed from the SIM card.</li>  </ul>  Transitioning between the provisioning and provisioned states may take some time.
	Value string `json:"value,omitempty"`
}
