/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/WunderkindNYC/telnyx-go

type InboundConfiguration struct {
	// This setting allows you to set the format with which the caller's number (ANI) is sent for inbound phone calls.
	AniNumberFormat string `json:"ani_number_format,omitempty"`
	DnisNumberFormat string `json:"dnis_number_format,omitempty"`
	// Defines the list of codecs that Telnyx will send for inbound calls to a specific number on your portal account, in priority order. This only works when the Connection the number is assigned to uses Media Handling mode: default. OPUS and H.264 codecs are available only when using TCP or TLS transport for SIP.
	Codecs []string `json:"codecs,omitempty"`
	// When set, this will limit the total number of inbound calls to phone numbers associated with this connection.
	ChannelLimit int32 `json:"channel_limit,omitempty"`
	// Generate ringback tone through 183 session progress message with early media.
	GenerateRingbackTone bool `json:"generate_ringback_tone,omitempty"`
	// When set, inbound phone calls will receive ISUP parameters via SIP headers. (Only when available and only when using TCP or TLS transport.)
	IsupHeadersEnabled bool `json:"isup_headers_enabled,omitempty"`
	// Enable PRACK messages as defined in RFC3262.
	PrackEnabled bool `json:"prack_enabled,omitempty"`
	// By default, Telnyx does not send caller-id information when the caller has chosen to hide this information. When this option is enabled, Telnyx will send the SIP header Privacy:id plus the caller-id information so that the receiver side can choose when to hide it.
	PrivacyZoneEnabled bool `json:"privacy_zone_enabled,omitempty"`
	// Defaults to true.
	SipCompactHeadersEnabled bool `json:"sip_compact_headers_enabled,omitempty"`
	// Time(sec) before aborting if connection is not made (min: 1, max: 20).
	Timeout1xxSecs string `json:"timeout_1xx_secs,omitempty"`
	// Time(sec) before aborting if call is unanswered (min: 1, max: 600).
	Timeout2xxSecs string `json:"timeout_2xx_secs,omitempty"`
}
