/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type ConnectionRtcpSettings struct {
	// BETA - Enable the capture and storage of RTCP messages to create QoS reports on the Telnyx Mission Control Portal.
	CaptureEnabled bool `json:"capture_enabled,omitempty"`
	// RTCP port by default is rtp+1, it can also be set to rtcp-mux
	Port string `json:"port,omitempty"`
	// RTCP reports are sent to customers based on the frequency set. Frequency is in seconds and it can be set to values from 5 to 3000 seconds.
	ReportFrequencySecs int32 `json:"report_frequency_secs,omitempty"`
}
