/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type Participant struct {
	// Call Control ID associated with the partiipant of the conference
	CallControlId string `json:"call_control_id"`
	// Uniquely identifies the call leg associated with the participant
	CallLegId string `json:"call_leg_id"`
	Conference *ParticipantConference `json:"conference"`
	// ISO 8601 formatted date of when the participant was created
	CreatedAt string `json:"created_at"`
	// Whether the conference will end and all remaining participants be hung up after the participant leaves the conference.
	EndConferenceOnExit bool `json:"end_conference_on_exit"`
	// Uniquely identifies the participant
	Id string `json:"id"`
	// Whether the participant is muted.
	Muted bool `json:"muted"`
	// Whether the participant is put on_hold.
	OnHold bool `json:"on_hold"`
	RecordType string `json:"record_type"`
	// Whether the conference will end after the participant leaves the conference.
	SoftEndConferenceOnExit bool `json:"soft_end_conference_on_exit"`
	// The status of the participant with respect to the lifecycle within the conference
	Status string `json:"status"`
	// ISO 8601 formatted date of when the participant was last updated
	UpdatedAt string `json:"updated_at"`
	// Array of unique call_control_ids the participant can whisper to..
	WhisperCallControlIds []string `json:"whisper_call_control_ids"`
}
