/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type CreateMessagingProfileRequest struct {
	// Specifies whether the messaging profile is enabled or not.
	Enabled bool `json:"enabled,omitempty"`
	// A user friendly name for the messaging profile.
	Name string `json:"name"`
	NumberPoolSettings *NumberPoolSettings `json:"number_pool_settings,omitempty"`
	UrlShortenerSettings *UrlShortenerSettings `json:"url_shortener_settings,omitempty"`
	// Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.
	WebhookApiVersion string `json:"webhook_api_version,omitempty"`
	// The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.
	WebhookFailoverUrl string `json:"webhook_failover_url,omitempty"`
	// The URL where webhooks related to this messaging profile will be sent.
	WebhookUrl string `json:"webhook_url,omitempty"`
}
