/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
// ServicePlan : Indicates the coverage of the termination regions. International and Global are the same but International may only be used for high volume/short duration Outbound Voice Profiles.
type ServicePlan string

// List of ServicePlan
const (
	US_ServicePlan ServicePlan = "us"
	INTERNATIONAL_ServicePlan ServicePlan = "international"
	GLOBAL_ServicePlan ServicePlan = "global"
)
