/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type SimCardRegistration struct {
	RegistrationCodes []string `json:"registration_codes"`
	// The group SIMCardGroup identification. This attribute can be <code>null</code> when it's present in an associated resource.
	SimCardGroupId string `json:"sim_card_group_id,omitempty"`
	// Status on which the SIM card will be set after being successful registered.
	Status string `json:"status,omitempty"`
	// Searchable tags associated with the SIM card
	Tags []string `json:"tags,omitempty"`
}
