/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/WunderkindNYC/telnyx-go

type NumberOrdersPhoneNumbers struct {
	Id string `json:"id,omitempty"`
	RecordType string `json:"record_type,omitempty"`
	PhoneNumber string `json:"phone_number,omitempty"`
	RegulatoryGroupId string `json:"regulatory_group_id,omitempty"`
	RegulatoryRequirements []NumberOrdersRegulatoryRequirements `json:"regulatory_requirements,omitempty"`
	// True if all requirements are met for a phone number, false otherwise
	RequirementsMet bool `json:"requirements_met,omitempty"`
	// The status of the phone number in the order
	Status string `json:"status,omitempty"`
}
