/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
// WebhookApiVersion : Determines which webhook format will be used, Telnyx API v1 or v2.
type WebhookApiVersion string

// List of WebhookApiVersion
const (
	1__WebhookApiVersion WebhookApiVersion = "1"
	2__WebhookApiVersion WebhookApiVersion = "2"
)
