/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type ReferRequest struct {
	// Use this field to add state to every subsequent webhook. It must be a valid Base-64 encoded string.
	ClientState string `json:"client_state,omitempty"`
	// Use this field to avoid execution of duplicate commands. Telnyx will ignore subsequent commands with the same `command_id` as one that has already been executed.
	CommandId string `json:"command_id,omitempty"`
	// Custom headers to be added to the SIP INVITE.
	CustomHeaders []CustomSipHeader `json:"custom_headers,omitempty"`
	// The SIP URI to which the call will be referred to.
	SipAddress string `json:"sip_address"`
	// SIP Authentication password used for SIP challenges.
	SipAuthPassword string `json:"sip_auth_password,omitempty"`
	// SIP Authentication username used for SIP challenges.
	SipAuthUsername string `json:"sip_auth_username,omitempty"`
}
