/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

// The containing element for the message content — Indicates that the message is highly structured. Parameters contained within provide the structure.
type Hsm struct {
	// The element name that indicates which template to use within the namespace
	ElementName string `json:"element_name"`
	Language *Language `json:"language"`
	// This field is an array of values to apply to variables in the template
	LocalizableParams []LocalizableParam `json:"localizable_params"`
	// The namespace that will be used
	Namespace string `json:"namespace"`
}
