/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type PhoneNumbersJobFailedOperation struct {
	Errors []ModelError `json:"errors,omitempty"`
	// The phone number's ID
	Id string `json:"id,omitempty"`
	// The phone number in e164 format.
	PhoneNumber string `json:"phone_number,omitempty"`
}
