/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/WunderkindNYC/telnyx-go

type InlineResponse20033Data struct {
	Id string `json:"id,omitempty"`
	RecordType string `json:"record_type,omitempty"`
	PhoneNumbers []NumberOrdersPhoneNumbers `json:"phone_numbers,omitempty"`
	// The count of phone numbers in the number order
	PhoneNumbersCount int32 `json:"phone_numbers_count,omitempty"`
	// The status of the order
	Status string `json:"status,omitempty"`
	// A customer reference string for customer look ups
	CustomerReference string `json:"customer_reference,omitempty"`
	// The connection id to set the number to upon acquiring the number
	ConnectionId string `json:"connection_id,omitempty"`
	// The messaging profile id to set the number to upon acquiring the number
	MessagingProfileId string `json:"messaging_profile_id,omitempty"`
	// A webhook URL for number order status updates
	WebhookUrl string `json:"webhook_url,omitempty"`
	// If above webhook URL fails, this URL will be used as a fail over
	WebhookFailoverUrl string `json:"webhook_failover_url,omitempty"`
	// An ISO 8901 datetime string denoting when the number order was created
	CreatedAt string `json:"created_at,omitempty"`
	// An ISO 8901 datetime string for when the number order was updated
	UpdatedAt string `json:"updated_at,omitempty"`
	// True if all requirements are met for every phone number, false otherwise
	RequirementsMet bool `json:"requirements_met,omitempty"`
}
