/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type CreateFqdnRequest struct {
	// ID of the FQDN connection to which this IP should be attached.
	ConnectionId string `json:"connection_id"`
	// The DNS record type for the FQDN. For cases where a port is not set, the DNS record type must be 'srv'. For cases where a port is set, the DNS record type must be 'a'. If the DNS record type is 'a' and a port is not specified, 5060 will be used.
	DnsRecordType string `json:"dns_record_type"`
	// FQDN represented by this resource.
	Fqdn string `json:"fqdn"`
	// Port to use when connecting to this FQDN.
	Port int32 `json:"port,omitempty"`
}
