/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type CreateRoomRequest struct {
	// The maximum amount of participants allowed in a room. If new participants try to join after that limit is reached, their request will be rejected.
	MaxParticipants int32 `json:"max_participants,omitempty"`
	// The unique (within the Telnyx account scope) name of the room.
	UniqueName string `json:"unique_name,omitempty"`
}
