/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type CreateManagedAccountRequest struct {
	// The name of the business for which the new managed account is being created, that will be used as the managed accounts's organization's name.
	BusinessName string `json:"business_name"`
	// The email address for the managed account. If not provided, the email address will be generated based on the email address of the manager account.
	Email string `json:"email,omitempty"`
	// Password for the managed account. If a password is not supplied, the account will not be able to be signed into directly. (A password reset may still be performed later to enable sign-in via password.)
	Password string `json:"password,omitempty"`
}
