/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type InlineResponse20030Data struct {
	RecordType string `json:"record_type,omitempty"`
	Id string `json:"id,omitempty"`
	UrlDomain string `json:"url_domain,omitempty"`
	UseCase string `json:"use_case,omitempty"`
}
