/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type Verification struct {
	CreatedAt string `json:"created_at"`
	Id string `json:"id"`
	// +E164 formatted phone number.
	PhoneNumber string `json:"phone_number"`
	// Identifies the type of the resource.
	RecordType string `json:"record_type,omitempty"`
	Status *VerificationStatus `json:"status"`
	// This is the number of seconds before the code of the request is expired. Once this request has expired, the code will no longer verify the user. Note: this will override the `default_timeout_secs` on the Verify profile.
	TimeoutSecs int32 `json:"timeout_secs,omitempty"`
	Type_ *VerificationType `json:"type"`
	UpdatedAt string `json:"updated_at"`
	// The identifier of the associated Verify profile.
	VerifyProfileId string `json:"verify_profile_id"`
}
