/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type NumberLookupRecord struct {
	CallerName *CallerName `json:"caller_name,omitempty"`
	Carrier *Carrier `json:"carrier,omitempty"`
	// Region code that matches the specific country calling code
	CountryCode string `json:"country_code,omitempty"`
	// Unused
	Fraud string `json:"fraud,omitempty"`
	// Hyphen-separated national number, preceded by the national destination code (NDC), with a 0 prefix, if an NDC is found
	NationalFormat string `json:"national_format,omitempty"`
	// E164-formatted phone number
	PhoneNumber string `json:"phone_number,omitempty"`
	Portability *Portability `json:"portability,omitempty"`
	// Identifies the type of record
	RecordType string `json:"record_type,omitempty"`
}
