/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

// IDs related to who ended the conference. It is expected for them to all be there or all be null
type ConferenceEndedBy struct {
	// Call Control ID which ended the conference
	CallControlId string `json:"call_control_id,omitempty"`
	// Call Session ID which ended the conference
	CallSessionId string `json:"call_session_id,omitempty"`
}
