/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
// ActivationStatus : Activation status
type ActivationStatus string

// List of ActivationStatus
const (
	NEW_ActivationStatus ActivationStatus = "New"
	PENDING_ActivationStatus ActivationStatus = "Pending"
	CONFLICT_ActivationStatus ActivationStatus = "Conflict"
	CANCEL_PENDING_ActivationStatus ActivationStatus = "Cancel Pending"
	FAILED_ActivationStatus ActivationStatus = "Failed"
	CONCURRED_ActivationStatus ActivationStatus = "Concurred"
	ACTIVATE_RDY_ActivationStatus ActivationStatus = "Activate RDY"
	DISCONNECT_PENDING_ActivationStatus ActivationStatus = "Disconnect Pending"
	CONCURRENCE_SENT_ActivationStatus ActivationStatus = "Concurrence Sent"
	OLD_ActivationStatus ActivationStatus = "Old"
	SENDING_ActivationStatus ActivationStatus = "Sending"
	ACTIVE_ActivationStatus ActivationStatus = "Active"
	CANCELED_ActivationStatus ActivationStatus = "Canceled"
)
