/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
import (
	"time"
)

type InlineResponse20026Data struct {
	// Identifies the type of the resource.
	RecordType string `json:"record_type,omitempty"`
	// Identifies the type of resource.
	Id string `json:"id,omitempty"`
	// +E.164 formatted phone number.
	PhoneNumber string `json:"phone_number,omitempty"`
	// Unique identifier for a messaging profile.
	MessagingProfileId string `json:"messaging_profile_id,omitempty"`
	// ISO 8601 formatted date indicating when the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ISO 8601 formatted date indicating when the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ISO 3166-1 alpha-2 country code.
	CountryCode string `json:"country_code,omitempty"`
	// The type of the phone number
	Type_ string `json:"type,omitempty"`
	Health *InlineResponse20026DataHealth `json:"health,omitempty"`
	// The messaging products that this number can be registered to use
	EligibleMessagingProducts []string `json:"eligible_messaging_products,omitempty"`
	// The messaging traffic or use case for which the number is currently configured.
	TrafficType string `json:"traffic_type,omitempty"`
	// The messaging product that the number is registered to use
	MessagingProduct string `json:"messaging_product,omitempty"`
	Features *InlineResponse20026DataFeatures `json:"features,omitempty"`
}
