/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

// Recording URLs in requested format. The URL is valid for as long as the file exists. For security purposes, this feature is activated on a per request basis.  Please contact customer support with your Account ID to request activation.
type CallRecordingSavedPayloadPublicRecordingUrls struct {
	// Recording URL in requested `mp3` format.
	Mp3 string `json:"mp3,omitempty"`
	// Recording URL in requested `wav` format.
	Wav string `json:"wav,omitempty"`
}
