/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
// EncryptedMedia : Enable use of SRTP or ZRTP for encryption. Valid values are those listed or null. Cannot be set to non-null if the transport_portocol is TLS.
type EncryptedMedia string

// List of EncryptedMedia
const (
	SRTP_EncryptedMedia EncryptedMedia = "SRTP"
	ZRTP_EncryptedMedia EncryptedMedia = "ZRTP"
)
