/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type InlineResponse2017Data struct {
	AccessToken string `json:"access_token,omitempty"`
	// ISO 8601 timestamp when the access token expires.
	AccessTokenExpiresAt string `json:"access_token_expires_at,omitempty"`
}
