/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx
import (
	"time"
)

type CallRecordingSavedPayload struct {
	// ID that is unique to the call and can be used to correlate webhook events.
	CallLegId string `json:"call_leg_id,omitempty"`
	// ID that is unique to the call session and can be used to correlate webhook events.
	CallSessionId string `json:"call_session_id,omitempty"`
	// Whether recording was recorded in `single` or `dual` channel.
	Channels string `json:"channels,omitempty"`
	// State received from a command.
	ClientState string `json:"client_state,omitempty"`
	// Call Control App ID (formerly Telnyx connection ID) used in the call.
	ConnectionId string `json:"connection_id,omitempty"`
	PublicRecordingUrls *CallRecordingSavedPayloadPublicRecordingUrls `json:"public_recording_urls,omitempty"`
	// ISO 8601 datetime of when recording ended.
	RecordingEndedAt time.Time `json:"recording_ended_at,omitempty"`
	// ISO 8601 datetime of when recording started.
	RecordingStartedAt time.Time `json:"recording_started_at,omitempty"`
	RecordingUrls *CallRecordingSavedPayloadRecordingUrls `json:"recording_urls,omitempty"`
}
