/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type InlineResponse404 struct {
	Code string `json:"code"`
	Title string `json:"title"`
	Detail string `json:"detail,omitempty"`
	Source *InlineResponse20021DataSource `json:"source,omitempty"`
	Meta *interface{} `json:"meta,omitempty"`
}
