/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type CreateNumberOrderDocumentRequest struct {
	// An ISO 8901 datetime string denoting when the number order document was uploaded.
	CreatedAt string `json:"created_at,omitempty"`
	// A customer reference string for customer look ups.
	CustomerReference string `json:"customer_reference,omitempty"`
	// The id of the file to associate as a number order document.
	FileId string `json:"file_id,omitempty"`
	Id string `json:"id,omitempty"`
	RecordType string `json:"record_type,omitempty"`
	RequirementType string `json:"requirement_type,omitempty"`
	// Unique id for a requirement.
	RequirementsId string `json:"requirements_id,omitempty"`
}
