/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type WhatsAppContactAddress struct {
	// City name
	City string `json:"city"`
	// Full country name
	Country string `json:"country"`
	// Two-letter country abbreviation
	CountryCode string `json:"country_code"`
	// State abbreviation
	State string `json:"state"`
	// Street number and name
	Street string `json:"street"`
	// Standard Values: HOME, WORK
	Type_ string `json:"type"`
	// ZIP code
	Zip string `json:"zip"`
}
