/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

// The links to download the recording files
type RecordingDownloadUrls struct {
	// Link to download the recording in mp3 format
	Mp3 string `json:"mp3,omitempty"`
	// Link to download the recording in wav format
	Wav string `json:"wav,omitempty"`
}
