/*
 * Telnyx API
 *
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * API version: 2.0.0
 * Contact: support@telnyx.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package telnyx

type PortingOrderDocuments struct {
	// identifies the invoice document
	Invoice string `json:"invoice,omitempty"`
	// identifies the loa document
	Loa string `json:"loa,omitempty"`
}
